
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.03
name: File-Find-Rule-PPI
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  PPI: 1.000
  File::Find::Rule: 0.20
  perl: 5.005
  Params::Util: 0.10
abstract: Add support for PPI queries to File::Find::Rule
