---
abstract: 'Add support for PPI queries to File::Find::Rule'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::Find::Rule::PPI
name: File-Find-Rule-PPI
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Find::Rule: 0.20
  PPI: 1.000
  Params::Util: 0.10
  perl: 5.005
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/File-Find-Rule-PPI
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/File-Find-Rule-PPI
version: 1.06
